apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nestlancer-dev

resources:
  - ../../base
  - ../../services/gateway
  - ../../services/ws-gateway
  - ../../services/auth
  - ../../services/users
  - ../../services/health
  - ../../infrastructure/postgresql
  - ../../infrastructure/redis-cache
  - ../../infrastructure/redis-pubsub
  - ../../infrastructure/rabbitmq

patches:
  - path: patches.yaml
