apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nestlancer

commonLabels:
  app.kubernetes.io/part-of: nestlancer
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - network-policy.yaml
  - ingress.yaml
  - pdb.yaml
  - service-account.yaml
