apiVersion: v1
kind: ServiceAccount
metadata:
  name: nestlancer-sa
  namespace: nestlancer
  labels:
    app.kubernetes.io/part-of: nestlancer
  annotations:
    eks.amazonaws.com/role-arn: "" # Set via kustomize overlay
