apiVersion: v1
kind: Service
metadata:
  name: messaging
  namespace: nestlancer
  labels:
    app.kubernetes.io/name: messaging
    app.kubernetes.io/part-of: nestlancer
spec:
  type: ClusterIP
  ports:
    - port: 3018
      targetPort: 3018
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: messaging
