export const ADMIN_CONFIG = {
  DASHBOARD_CACHE_TTL: 300, // 5 minutes
  AUDIT_RETENTION_DAYS: 365,
  MAX_IMPERSONATION_DURATION_HOURS: 4,
  BACKUP_S3_BUCKET: process.env.AWS_S3_BUCKET_PRIVATE || 'nestlancer-private-backups',
  BACKUP_RETENTION_DAYS: 30,
  WEBHOOK_MAX_RETRIES: 5,
  WEBHOOK_BACKOFF_BASE_SECONDS: 10,
};
