apiVersion: v1
kind: Service
metadata:
  name: webhooks
  namespace: nestlancer
  labels:
    app.kubernetes.io/name: webhooks
    app.kubernetes.io/part-of: nestlancer
spec:
  type: ClusterIP
  ports:
    - port: 3025
      targetPort: 3025
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: webhooks
