apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cache-config
  namespace: nestlancer
data:
  redis.conf: |
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    appendonly no
    save ""
    tcp-keepalive 300
    timeout 0
