apiVersion: v1
kind: Service
metadata:
  name: health
  namespace: nestlancer
  labels:
    app.kubernetes.io/name: health
    app.kubernetes.io/part-of: nestlancer
spec:
  type: ClusterIP
  ports:
    - port: 3010
      targetPort: 3010
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: health
