apiVersion: v1
kind: Service
metadata:
  name: portfolio
  namespace: nestlancer
  labels:
    app.kubernetes.io/name: portfolio
    app.kubernetes.io/part-of: nestlancer
spec:
  type: ClusterIP
  ports:
    - port: 3021
      targetPort: 3021
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: portfolio
