apiVersion: v1
kind: Service
metadata:
  name: contact
  namespace: nestlancer
  labels:
    app.kubernetes.io/name: contact
    app.kubernetes.io/part-of: nestlancer
spec:
  type: ClusterIP
  ports:
    - port: 3023
      targetPort: 3023
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: contact
