apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-worker
  namespace: nestlancer
  labels:
    app.kubernetes.io/name: analytics-worker
    app.kubernetes.io/component: analytics-worker
    app.kubernetes.io/part-of: nestlancer
    tier: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: analytics-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: analytics-worker
        app.kubernetes.io/component: analytics-worker
        app.kubernetes.io/part-of: nestlancer
        tier: worker
    spec:
      serviceAccountName: nestlancer-sa
      containers:
        - name: analytics-worker
          image: ghcr.io/nestlancer/nestlancer-analytics-worker:latest
          envFrom:
            - configMapRef:
                name: nestlancer-config
            - secretRef:
                name: nestlancer-secrets
          env:
            - name: SERVICE_NAME
              value: "analytics-worker"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      restartPolicy: Always
