apiVersion: apps/v1
kind: Deployment
metadata:
  name: outbox-poller
  namespace: nestlancer
  labels:
    app.kubernetes.io/name: outbox-poller
    app.kubernetes.io/component: outbox-poller
    app.kubernetes.io/part-of: nestlancer
    tier: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: outbox-poller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: outbox-poller
        app.kubernetes.io/component: outbox-poller
        app.kubernetes.io/part-of: nestlancer
        tier: worker
    spec:
      serviceAccountName: nestlancer-sa
      containers:
        - name: outbox-poller
          image: ghcr.io/nestlancer/nestlancer-outbox-poller:latest
          envFrom:
            - configMapRef:
                name: nestlancer-config
            - secretRef:
                name: nestlancer-secrets
          env:
            - name: SERVICE_NAME
              value: "outbox-poller"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      restartPolicy: Always
