apiVersion: v1
kind: ConfigMap
metadata:
  name: nestlancer-config
data:
  NODE_ENV: "production"
  LOG_LEVEL: "warn"
  FRONTEND_URL: "https://nestlancer.com"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-gateway
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: 2
