apiVersion: v1
kind: ConfigMap
metadata:
  name: nestlancer-config
data:
  DATABASE_URL: "postgresql://nl_db_user:dev-pg-c2e3f4g5h6i7@postgres-primary:5432/nl_dev_db?schema=public"
  DATABASE_READ_URL: "postgresql://nl_db_user:dev-pg-c2e3f4g5h6i7@postgres-replica:5432/nl_dev_db?schema=public"
  REDIS_CACHE_URL: "redis://:dev-rcache-p4q5r6s7t8u9@redis-cache:6379/0"
  REDIS_PUBSUB_URL: "redis://:dev-rpub-v0w1x2y3z4a5@redis-pubsub:6379/1"
  RABBITMQ_URL: "amqp://admin:dev-rmq-b6c7d8e9f0g1@rabbitmq:5672/app_vhost"
  MEILISEARCH_URL: "http://meilisearch:7700"
  INFISICAL_URL: "http://infisical:8080"
