apiVersion: v1
kind: Service
metadata:
  name: payments
  namespace: nestlancer
  labels:
    app.kubernetes.io/name: payments
    app.kubernetes.io/part-of: nestlancer
spec:
  type: ClusterIP
  ports:
    - port: 3017
      targetPort: 3017
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: payments
