apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-pubsub
  namespace: nestlancer
spec:
  serviceName: redis-pubsub
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-pubsub
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-pubsub
        app.kubernetes.io/part-of: nestlancer
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          command: ["redis-server"]
          args:
            - "--maxmemory-policy"
            - "noeviction"
            - "--appendonly"
            - "no"
            - "--save"
            - ""
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 10
